### ISSUE TITLE
Procyon taking too much time.

### ISSUE THREAD

**Issue by vjex** [linkedin/qark#10]
When the decompiling process is going on , CFR and JD Core finishes it properly but Procyon is stuck in the middle for a long time , even interrupting the compilation with CRTL+C is not helping .

**Comment by signedbit** [comment]
That seems to be a problem with Procyon. I've experienced the same thing when using http://www.secureteam.net/Java-Decompiler.aspx which is powered by Procyon. I haven't looked into the problem yet. I recently used Procyon to export a fairly large jar file (~1100 classes) with https://github.com/Konloch/bytecode-viewer. It did lag a bit, I thought it had frozen like the SecureTeam's d4j usually does but it did complete. Perhaps bytecode-viewer somehow addressed the problem.

**Comment by signedbit** [comment]
Nevermind about bytecode-viewer. I just looked at the code for how it handles Procyon, I don't see anything special to prevent lag. Furthermore, I just ran Procyon (0.5.30) on the same jar and it went fine. It did have some noticeable delay (which could be amplified on a normal machine, this one is quite powerful), and it lagged for a few seconds on one method where it eventually threw a StackOverflowError.

**Comment by SecBro1** [comment]
Avinash,

If you encounter this in the future, wait for at least one of the other two
decompilers to finish, then press the C key, without Ctrl, as it states at
the bottom of the screen. This will start the static code analysis with
whatever had been decompiled to that point.

Thanks,
Tony

When the decompiling process is going on , CFR and JD Core finishes it
properly but Procyon is stuck in the middle for a long time , even
interrupting the compilation with CRTL+C is not helping .

—
Reply to this email directly or view it on GitHub
<https://github.com/linkedin/qark/issues/10>.

**Comment by tushardalvi** [comment]
Thanks for the feedback. We have seen similar behavior for Procyon when we run our tests, and we introduced the ability to continue with partial decompilation for the exact same reason. @vjex, the escape sequence to break out of the decompilation phase is just "c" and not "Crtl+C". Ctrl+C will exit the program.

Cheers.

**Comment by vjex** [comment]
Thanks for clearing out.
and yes I also observe that Procyon does complete the scan albeit the lag.
