### ISSUE TITLE
Adding modules?

### ISSUE THREAD

**Issue by Kkevsterrr** [linkedin/qark#118]
What is involved in adding custom modules to qark?

**Comment by nwalsh1995** [comment]
You can see example code in the `qark/plugins` folder. There is a class that is there to help you, `PluginUtil.py`.

Right now we don't have proper documentation on how to create plugins, but it is on the roadmap.

**Comment by nwalsh-lnk** [comment]
Documentation on plugins are in the wiki here: [https://github.com/linkedin/qark/wiki/Plugins](https://github.com/linkedin/qark/wiki/Plugins). Closing.
