### ISSUE TITLE
problem  with reporting

### ISSUE THREAD

**Issue by shuangy0520** [linkedin/qark#121]
Hi, 
I use qark to test vulnerabilities exist in the app. When the analyze is finished, I got a problem with report error---No Html report generated. So please tell how can I get the report.Thanks.

**Comment by nwalsh1995** [comment]
Can you provide more logs? The html report can fail for a lot of reasons so having more information will help us figure out the problem.

**Comment by nwalsh-lnk** [comment]
Closing as it seems the problem has been remediated.
