### ISSUE TITLE
pre load terminal

### ISSUE THREAD

**Issue by AjaxFB** [linkedin/qark#145]
yes c or echo "c" dont work on qark, python error(in cbreak save_mode = termios.tcgetattr(self.keyboard_fd)).
I cant make manually on 3000 apks,

**Comment by nwalsh1995** [comment]
Could you provide a screenshot of what is happening when the error occurs?

**Comment by nwalsh-lnk** [comment]
I believe you should be able to run QARK in automated mode which should allow you not to have to compile manually. Closing ticket from no response.
