### ISSUE TITLE
Build Failed

### ISSUE THREAD

**Issue by alonf1983** [linkedin/qark#151]
Hi
when the qark tries to buid the APK i get the below error:

Error: org.gradle.process.internal.ExecException: A problem occurred starting process 'command '/root/Downloads/qark/qark/android-sdk_r24.3.4-linux/android-sdk-linux/build-tools/21.1.2/aapt''
:app:mergeDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Error: org.gradle.process.internal.ExecException: A problem occurred starting process 'command '/root/Downloads/qark/qark/android-sdk_r24.3.4-linux/android-sdk-linux/build-tools/21.1.2/aapt''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

could you help me to solve it?

Thanks

**Comment by nwalsh-lnk** [comment]
Hi @alonf1983 it appears we have a few of these issues. Linking them here.

#116 
#103 
#72 

This will become the new master to track these issues.

**Comment by alonf1983** [comment]
@nwalsh-lnk  Thanks for the update
do you have ETA for this fix?

**Comment by nwalsh1995** [comment]
Hi @alonf1983, no timeline yet. 

We are currently working on our next major release, [v2](https://github.com/linkedin/qark/wiki/v2:-The-future). That should fix many of these issues. Once someone can get to the build APK code we can push a fix to the master.

**Comment by nwalsh-lnk** [comment]
@alonf1983, v2 should land in master within a month or so. You can use the current `v2` branch as it is right now and maintain about the same amount of functionality as the original QARK. When you checkout the v2 branch make sure to `python setup.py install` and then use the tool by running the `qark` command.

If you want to get more information on why this specific command is failing, you can try running:
`aapt dump badging {path_to_apk}`

**Comment by blue31u** [comment]
I was having the same or similar issues during the app build part of the python script. I fixed it by opening Andriod Studuio files within the QARK directory and found that I did not have the build tools version (21.1.2) which QARK is dependent on. After downloading the build tools it worked for me. Maybe you could add a check for the build tool version and download it if needed?

**Comment by nwalsh-lnk** [comment]
We have just pushed a new version of QARK that solves a lot of problems and enhances the code.

As a result we will be closing out all tickets for the older version since we no longer support it. If this issue persists in the new version please create a new ticket.

**Comment by nocomp** [comment]
hi @neilatli @nwalsh-lnk @blue31u @chriseppstein 
been reading this toppic and thx that solved the build.
BUT the generated apk doesn t work, got force close when launching it.
3 days trying to get this tool working, re installed a 16.04 ubuntu, with the right java 8, the right build tools version, the right everything, and now apk gets build, but, it doesn t work.
i ve read in a topic that maybe you have to manyally copy some files on the phone, but doesn t say wich one.
did any of you got it working? do you mind to share how you ve done?
thxx for your time
