### ISSUE TITLE
Inappropriate ioctl for device

### ISSUE THREAD

**Issue by prabintim** [linkedin/qark#175]
I am running qark on Bitrise CI server and I am seeing this error:
```
Traceback (most recent call last):
  File "/bitrise/src/build/qark/qark/qarkMain.py", line 1281, in <module>
    nonAutomatedParseArgs()
  File "/bitrise/src/build/qark/qark/qarkMain.py", line 462, in nonAutomatedParseArgs
    main()
  File "/bitrise/src/build/qark/qark/qarkMain.py", line 790, in main
    unpackAPK.decompile(common.pathToDEX)
  File "/bitrise/src/build/qark/qark/modules/unpackAPK.py", line 162, in decompile
    with common.term.cbreak():
  File "/usr/lib/python2.7/contextlib.py", line 17, in __enter__
    return self.gen.next()
  File "/bitrise/src/build/qark/qark/lib/blessed/terminal.py", line 572, in cbreak
    save_mode = termios.tcgetattr(self.keyboard_fd)
termios.error: (25, 'Inappropriate ioctl for device')
```

This error occurs because the it accepts key input to cancel the build anytime:
```
Decompilation may hang/take too long (usually happens when the source is obfuscated).
At any time,Press C to continue and QARK will attempt to run SCA on whatever was decompiled.
```

Here's my command to run qark:
```
python "${source_dir}/build/qark/qark/qarkMain.py" -s 1 -p "${path_to_apk}/app-prod-debug.apk" -e 1 -d 10 -b ${ANDROID_HOME}
```

The Terminal on Bitrise CI returns `dumb` when I execute `set | grep TERM` meaning the terminal has limited capabilities. I tried `export TERM=linux` but still not luck. 

How do I resolve this step?

**Comment by nwalsh1995** [comment]
Hi @prabintim, can you try the solution proposed in #51 ?

We are working on a [new version](https://github.com/linkedin/qark/wiki/v2:-The-future) of QARK that should not have these problems.

**Comment by prabintim** [comment]
Hi @nwalsh1995 , yes I tried that solution but there's no syntax as `script --return`, at least on my Mac. I get `usage: script [-adkpqr] [-t time] [file [command ...]]`. Would you be able to post the modified version of that solution that might work?

**Comment by nwalsh1995** [comment]
Try `script "<command>"` instead. The arguments for `script` on Mac are different than the Linux version. You can see the arguments that it takes with `man script`

**Comment by dmarjanovic** [comment]
I have the same issue on macOS & Jenkins.

@prabintim have you managed to find a working solution?

@nwalsh1995 are you maybe aware of any alternative? `script "<command>"` gives me `No such file or directory`. Thanks
