### ISSUE TITLE
Java Version Error

### ISSUE THREAD

**Issue by alonf1983** [linkedin/qark#183]
Hi,
when the qark tries to build the APK, the following error showed:
"Could not determine java version from '9.0.4'."

in my Mac I have version 9.0.4:

Alons-MacBook-Pro:qark alonf$ java --version
java 9.0.4
Java(TM) SE Runtime Environment (build 9.0.4+11)
Java HotSpot(TM) 64-Bit Server VM (build 9.0.4+11, mixed mode)

how can I solve this?

**Comment by nwalsh-lnk** [comment]
Hi @alonf1983, the problem actually is coming from Gradle.

https://discuss.gradle.org/t/could-not-determine-java-version-from-9-0-1/24457/3

If you replace the downloaded SDK with a newer version it should work. You can specify a path to the SDK with `-b` flag.

**Comment by alonf1983** [comment]
Hi
do you have ETA to fix the code with the new SDK?

**Comment by alonf1983** [comment]
Hi again
I have tried to use the newest SDK with the command:
python qarkMain.py -p apk.apk --source=1 -b /Users/XXX/Library/Android/sdk/sources/android-27 -e 1 -I

however, I still get the error:
FAILURE: Build failed with an exception.

* What went wrong:
Could not determine java version from '10'.


could you help me?

**Comment by nwalsh-lnk** [comment]
We have just pushed a new version of QARK that solves a lot of problems and enhances the code.

As a result we will be closing out all tickets for the older version since we no longer support it. If this issue persists in the new version please create a new ticket.
