### ISSUE TITLE
ReactNative Support

### ISSUE THREAD

**Issue by DanielStevenLewis** [linkedin/qark#184]
Just to confirm: QARK works with all Android apks, including ReactNative apks, right?

**Comment by nwalsh1995** [comment]
Hi @DanielStevenLewis,

We run the following tools/decompilers on APKS:

1. APKTool
2. JDCore
3. Procyon
4. CFR

If all of these operate properly on ReactNative then I don't see why it wouldn't work.

**Comment by nwalsh-lnk** [comment]
We have just pushed a new version of QARK that solves a lot of problems and enhances the code.

As a result we will be closing out all tickets for the older version since we no longer support it. If this issue persists in the new version please create a new ticket.
