### ISSUE TITLE
Jenkins qark issue- when building, qark analysis is done but half and build says succesfull 

### ISSUE THREAD

**Issue by shagundepan95** [linkedin/qark#185]
When im building my job qark analysis takes place in the execute shell window but then as soon as procyon hits 99% build says successful and this leads to incomplete qark analysis. Also if I write the same command in my ec2 instance the command runs successfully and also complete the analysis.. Any ideas why is it happening?

**Comment by nwalsh1995** [comment]
Hi @shagundepan95, have you seen the following issues?

#42 
#31 

If the solution there doesn't work I would recommend you to checkout the new `v2` branch and use that.

**Comment by nwalsh-lnk** [comment]
We have just pushed a new version of QARK that solves a lot of problems and enhances the code.

As a result we will be closing out all tickets for the older version since we no longer support it. If this issue persists in the new version please create a new ticket.
