### ISSUE TITLE
Failed to download dex2jar jar

### ISSUE THREAD

**Issue by Patryck95** [linkedin/qark#189]
Hi,
I am passing this command in cli:

python qarkMain.py --source 1 --pathtoapk /home/patryck/Desktop/100_APKS/AdTime-ead57e70c29080bf41ce7675df115055.apk --reportdir /home/patryck/Desktop/

and the tool sends me to interactive mode.

**Comment by nwalsh1995** [comment]
Hi @Patryck95, we are recommending users to use the `v2` branch. Please checkout that branch and run `pip install .` in its directory. We believe that branch to be far more stable and overall better than the master branch.

It is still in its development which is why it is not the new 'master'. However, it properly mimics most of the functionality from the original QARK.

**Comment by Patryck95** [comment]
Hi,
i have done what you said, but then when i try to execute the file qark.py and i have lots of import problems. I think that what's missing is some sys.path.insert like:
sys.path.insert(0, os.path.dirname(os.path.realpath(__file__)) + '/decompiler')

Can you run it this branch with python 2.x?

**Comment by nwalsh1995** [comment]
After `pip install .` it should install all the requirements, all you need to do to run the new version of QARK is to type `qark` in the command line (instead of pointing your python at it like `python qark.py`.

**Comment by Patryck95** [comment]
Hi,
Event if i do that i still got this import errors:

root@root:/home/patryck/qark/qark-2# qark
Traceback (most recent call last):
  File "/usr/local/bin/qark", line 7, in <module>
    from qark.qark import cli
  File "/usr/local/lib/python2.7/dist-packages/qark/qark.py", line 9, in <module>
    from qark.report import Report
  File "/usr/local/lib/python2.7/dist-packages/pluginbase.py", line 410, in plugin_import
    fromlist, level)
  File "/usr/local/lib/python2.7/dist-packages/qark/report.py", line 5, in <module>
    from jinja2 import Environment, PackageLoader, select_autoescape, Template
ImportError: cannot import name select_autoescape

**Comment by nwalsh1995** [comment]
It seems like your jinja2 installation is old. You might want to try to reinstall QARK using the steps above while using a [virtual environment](http://docs.python-guide.org/en/latest/dev/virtualenvs/).

Can you run the command `pip freeze` and paste its output here? Can you run `python --version` and paste its output here as well?

**Comment by Patryck95** [comment]
Hi,
Sorry for the late reply:
root@root:/home/patryck/qark/qark-2#pip freeze
adium-theme-ubuntu==0.3.4
amqp==2.2.2
asn1crypto==0.24.0
auth==0.5.3
AxmlParserPY==0.1
backports-abc==0.5
beautifulsoup4==4.6.0
billiard==3.5.0.3
blessed==1.14.2
blessings==1.6.1
blinker==1.4
celery==4.1.0
certifi==2018.1.18
cffi==1.11.4
chardet==3.0.4
click==6.7
colorama==0.3.9
coloredlogs==9.0
configparser==3.5.0
cryptography==2.1.4
Cython==0.27.3
Django==1.11.7
dnspython==1.15.0
ecdsa==0.13
enum34==1.1.6
eventlet==0.22.1
falcon==1.4.1
Flask==0.12.2
Flask-SQLAlchemy==2.3.2
funcsigs==1.0.2
future==0.16.0
google-api-python-client==1.6.5
greenlet==0.4.13
gunicorn==19.7.1
html5lib==1.0.1
httplib2==0.10.3
humanfriendly==4.8
idna==2.6
ipaddress==1.0.19
itsdangerous==0.24
javalang==0.11.0
Jinja2==2.8
kombu==4.1.0
lxml==4.1.1
MarkupSafe==0.23
mock==2.0.0
mongoengine==0.15.0
monotonic==1.4
mysql-connector-python==2.0.4
mysql-utilities==1.6.1
mysqlclient==1.3.7
ndg-httpsclient==0.4.0
numpy==1.14.0
oauth2client==4.1.2
paramiko==1.16.0
pbr==3.1.1
pdfkit==0.6.1
peewee==3.1.0
pexpect==4.0.1
pluginbase==0.5
ply==3.11
progressbar==2.3
psutil==5.4.3
ptyprocess==0.5
pyasn1==0.4.2
pyasn1-modules==0.2.1
pycparser==2.18
pycrypto==2.6.1
pymongo==3.6.0
PyMySQL==0.8.0
pyodbc==3.0.7
pyOpenSSL==17.5.0
pysqlite==2.7.0
pystan==2.17.1.0
python-mimeparse==1.6.0
pytz==2017.3
qark==2.0
requests==2.18.4
requirements==0.1
rsa==3.4.2
singledispatch==3.4.0.3
six==1.11.0
SQLAlchemy==1.2.4
sqlparse==0.1.18
tornado==4.5.3
uncurl==0.0.8
unity-lens-photos==1.0
uritemplate==3.0.0
urlgrabber==3.10.2
urllib3==1.22
vine==1.1.4
wcwidth==0.1.7
webencodings==0.5.1
Werkzeug==0.14.1
wget==3.2
xerox==0.4.1
Yapsy==1.11.223
yara-python==3.5.0.999

root@root:/home/patryck/qark/qark-2# python --version
Python 2.7.12

**Comment by nwalsh1995** [comment]
We have changed our `pip install` process so that anything that needs to be upgraded will be upgraded for you. Please try pulling the newest changes and running `pip install .`

**Comment by Patryck95** [comment]
Hi, sorry for the late reply,

I have done what you asked and now it does not give me import errors, however when I run this command:

qark --build-path /home/patryck/Desktop/ --apk /home/patryck/Desktop/100_APKS/AdobeScan-1e98983a447acd206b4de5221ff2f1c2.apk

it gives me:

Decompiling...
Failed to download dex2jar jar

Any ideas in what am I missing?
