### ISSUE TITLE
why not tranlate tabs to 4 spaces?

### ISSUE THREAD

**Issue by demonkit** [linkedin/qark#20]
??

**Comment by SecBro1** [comment]
Yeah, yeah. It's a habit with me. It's not my fault computers are broken.

When I get a chance, I'll go in and translate all the files to use 4 spaces instead. If you're using a half-way decent IDE, it should have an option for you to do this yourself, so you don't have to deal with it.

**Comment by neilatli** [comment]
Fixed with PR #107
