### ISSUE TITLE
v2 - i can't analyze 

### ISSUE THREAD

**Issue by ErnestoRG95** [linkedin/qark#219]
I try to run referencing the android studio project root directory and the src code directory.
![sin titulo](https://user-images.githubusercontent.com/25586003/38354389-b903fd3c-38b9-11e8-8f29-c5e58e7bd64b.jpg)

The real minSDK is 16.

**Comment by nwalsh1995** [comment]
Are you just saying the minSDK is wrong or are you getting an error?

**Comment by ErnestoRG95** [comment]
I'm saying that it possibly is a bug, because the app that i'm trying to analyze is min SDK 16 and qark gives me the report that i posted. If is not and someone can help me, i will appreciate.

**Comment by nwalsh1995** [comment]
What does your androidmanifest look like? 

If you didn't supply an android manifest it will default to a lower version.

**Comment by nwalsh1995** [comment]
It attempts to find the android manifest as a child of the directory, or inside the APK you are passing.

**Comment by nwalsh1995** [comment]
Hi @ErnestoRG95, thanks for digging into this. I thought this functionality was already existing for every type, but it is correct it was only functional for APKs.

I have made PR #220 to resolve this. It should be merged soon, please update when it merges and let me know if it fixes your problem.

**Comment by nwalsh-lnk** [comment]
Closing out for inactivity.
