### ISSUE TITLE
Support multiple devices

### ISSUE THREAD

**Issue by andresriancho** [linkedin/qark#22]
```
BUILD SUCCESSFUL

Total time: 4 mins 18.931 secs
Do you want to install this to your device? (y/n)y
INFO - Installing...
INFO - The apk can be found in the /home/pablo/tools/qark/build/qark directory
error: more than one device/emulator
- waiting for device -
...
error: more than one device/emulator
- waiting for device -
```

Instead of looping there, give the user the option to choose which device to use.

**Comment by SecBro1** [comment]
Should be a reasonable accommodation. We'll take a look at it.

Thanks for w3af BTW :)

**Comment by nwalsh-lnk** [comment]
We have just pushed a new version of QARK that solves a lot of problems and enhances the code.

As a result we will be closing out all tickets for the older version since we no longer support it. If this issue persists in the new version please create a new ticket.
