### ISSUE TITLE
Pyhton3 UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte

### ISSUE THREAD

**Issue by nafuti** [linkedin/qark#236]
Run into this error `UnicodeDecodeError: 'utf-8' codec can't decode byte 0x89 in position 0: invalid start byte` when QARK started running scans. Its in `"/usr/local/lib/python3.5/dist-packages/qark/scanner/plugin.py", line 136` as per the screenshot.
![screenshot of error](http://imgur.com/vPKG0I0l.png)

Possible solutions were ignoring the offending characters OR using the `latin-1` encoding. Both these solutions didn't give me that error. Could send a PR but don't know which one of these solutions is acceptable by you.

**Comment by nwalsh1995** [comment]
Hi @nafuti, pr #235 addresses this in QARK v2. It looks like I came across the same problem as you.

**Comment by nwalsh1995** [comment]
I have just merged that PR. Closing this issue out.
