### ISSUE TITLE
support for python 3

### ISSUE THREAD

**Issue by einhverfr** [linkedin/qark#24]
Hi

I am noticing a lot of Python 3.x support code, but when I try to run it under Python 3, I get errors like

```
  File "qark.py", line 115
    print "Version 0.8"
                      ^
SyntaxError: Missing parentheses in call to 'print'
```

This is unintentional?

**Comment by SecBro1** [comment]
Support for Python 3 is on the roadmap, just haven't had the time to go through and clean up all version specific stuff.

**Comment by tushardalvi** [comment]
Thanks for your input. We plan to have a docker image of QARK released soon. Apologies for not getting this sooner.
