### ISSUE TITLE
Support for homebrew or pip?

### ISSUE THREAD

**Issue by commjoen** [linkedin/qark#254]
Hi there,
I was wondering: is it possible to get support for homebrew or pip so that I can directly download and install the tool on mac os x?

With kind regards,
Jeroen

**Comment by nwalsh1995** [comment]
Hi @commjoen, the new version of qark is pip installable and will be shortly read to be published to PyPi. I will close out this issue once we have published it.

**Comment by robertlagrant** [comment]
@nwalsh-lnk any progress on this?

**Comment by robertlagrant** [comment]
@nwalsh-lnk nice - thanks!

**Comment by commjoen** [comment]
Thanks!
