### ISSUE TITLE
got erroron windows 10

### ISSUE THREAD

**Issue by aeguy** [linkedin/qark#258]
c:\qark\qark>py qarkMain.py
  File "qarkMain.py", line 104
    print str(pathToAPK.rsplit(".",1)[0]).rsplit("/",1)[0] + "/apktool" + "/AndroidManifest.xml"
            ^
SyntaxError: invalid syntax

ive done installed Python 3 and update sdk for windows. But there still error, can you tell me about that problem? Thank you very much.

**Comment by nwalsh1995** [comment]
The master QARK code is Python 2.7, not python 3, which is why you are getting this error. Additionally, use the v2 branch if you want Windows support. If you face any problems during that install please make a new issue.
