### ISSUE TITLE
v2-start qark.py

### ISSUE THREAD

**Issue by aeguy** [linkedin/qark#260]
Traceback (most recent call last):
  File "qark.py", line 50, in <module>
    from lib.pyfiglet import Figlet
  File "/home/eguy/qark-0.9-alpha.10/lib/pyfiglet/__init__.py", line 10, in <module>
    import pkg_resources
![screenshot from 2018-10-14 19-29-27](https://user-images.githubusercontent.com/36437636/46916654-9fc9d600-cfe7-11e8-8451-2a92da86eded.png)

any idea to fix it ?

**Comment by nwalsh1995** [comment]
@aeguy it is a problem with your Python environment. Please see solutions from SO: https://stackoverflow.com/a/10538412

**Comment by aeguy** [comment]
@nwalsh1995 master, i found this error. Can you advice me to fix it, thank you master.
![screenshot from 2018-10-29 21-34-09](https://user-images.githubusercontent.com/36437636/47657038-e9f3af80-dbc2-11e8-9069-42205c513412.png)
