### ISSUE TITLE
Sometimes got stuck during static code analysis

### ISSUE THREAD

**Issue by JackDavid127** [linkedin/qark#261]
Even with small APKs like 16MiB. The python process just went sleeping like dead lock triggered. Can this static code analysis process be changed to single-thread, one task at a time?

**Comment by ziliang2xiaoxiao** [comment]
I have the same problem.

**Comment by nwalsh1995** [comment]
What branch of the code are you running on?

**Comment by JackDavid127** [comment]
> What branch of the code are you running on?

On branch master.

I strongly recommend adding parallelism options for the command line. I had to change the code in qarkMain.py to let those static analysis plugins execute one by one and it finally worked.

**Comment by nwalsh-lnk** [comment]
We have just pushed a new version of QARK that solves a lot of problems and enhances the code.

As a result we will be closing out all tickets for the older version since we no longer support it. If this issue persists in the new version please create a new ticket.
