### ISSUE TITLE
ERROR - failed to write report

### ISSUE THREAD

**Issue by geeeeeeeeek** [linkedin/qark#262]
```
ERROR - failed to write report
Traceback (most recent call last):
  File "/Users/ztong/Code/qark/qark/modules/report.py", line 199, in writeSection
    pre_rendered_html2.find("div", id=str(section[sec] + "-issues-list")).append(new_div_tag_1)
AttributeError: 'NoneType' object has no attribute 'append'
```

MacOS Mojave

**Comment by nwalsh1995** [comment]
Hi @geeeeeeeeek, please switch the branch to v2 and install the code from there and try again.

**Comment by nwalsh-lnk** [comment]
We have just pushed a new version of QARK that solves a lot of problems and enhances the code.

As a result we will be closing out all tickets for the older version since we no longer support it. If this issue persists in the new version please create a new ticket.
