### ISSUE TITLE
Get error in analyzing the apk. Error: UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 54: ordinal not in range(128)

### ISSUE THREAD

**Issue by owenxu10** [linkedin/qark#266]
After pulling the new commit, the QARK can't do the analysis. It shows error 

> UnicodeDecodeError: 'ascii' codec can't decode byte 0xe1 in position 54: ordinal not in range(128)

Could you check that?

**Comment by nwalsh1995** [comment]
Can you show the whole stack trace so we can see where the error came from?

**Comment by nwalsh-lnk** [comment]
This error might have been fixed in #286 but regardless this ticket hasn't been updated in 20 days. Closing.
