### ISSUE TITLE
errors with installation of the new version

### ISSUE THREAD

**Issue by alonf1983** [linkedin/qark#267]
Hi
once i tried to install  it with the command:

pip install . --user

i get rhe error:

error: can't copy 'qark/ate/tmp/pip-req-build-s4QKn3/qark/lib/decompilers/jd-core-java-1.2.jar': doesn't exist or not a regular file
    
    ----------------------------------------
Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/tmp/pip-req-build-s4QKn3/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /private/tmp/pip-record-8WmidI/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /private/tmp/pip-req-build-s4QKn3/

could you help me?

i'm using macOS 10.14.1

Thanks

**Comment by nwalsh-lnk** [comment]
Is this happening on install? Can you paste a copy of the commands you ran to get to this point? I haven't been able to reproduce.

**Comment by alonf1983** [comment]
it was issue in my mac. sorry
