### ISSUE TITLE
Failed to download dex2jar jar

### ISSUE THREAD

**Issue by alonf1983** [linkedin/qark#272]
Hi
trying to execute qark, however, get the following errors.
Could you please help?

qark@localhost:~/qark$ qark --apk ../wy.apk 
Decompiling...
Failed to download dex2jar jar
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/qark/decompiler/decompiler.py", line 392, in download_dex2jar
    download_file(DEX2JAR_URL, os.path.join(LIB_PATH, "temp_dex2jar.zip"))
  File "/usr/local/lib/python2.7/dist-packages/qark/decompiler/decompiler.py", line 343, in download_file
    with open(download_path, "wb") as download_path_file:
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/qark/decompiler/../lib/temp_dex2jar.zip'
Failed to download dex2jar jar
qark@localhost:~/qark$

**Comment by nwalsh-lnk** [comment]
I was able to triage this. Going to be pushing a fix today.

**Comment by nwalsh-lnk** [comment]
Fixed some things in the release and have updated. Please try the following:

```
~ pip uninstall qark
~ pip install --user qark
~ qark --help
```
