### ISSUE TITLE
running scans error on kalilinux

### ISSUE THREAD

**Issue by aeguy** [linkedin/qark#273]
![screenshot from 2018-11-22 03-36-04](https://user-images.githubusercontent.com/36437636/48867256-315b0d80-ee08-11e8-97ed-48efd5daaee7.png)

running scan after decompile got error. How i can fix it Master ? Thankyou very much

**Comment by nwalsh1995** [comment]
Hi I have pushed a change that should fix this issue. Can you upgrade your version of `qark` from pypi? The correct version is `qark==2.2.1`.

`pip install qark --upgrade`

**Comment by aeguy** [comment]
file:///root/Pictures/Screenshot%20from%202018-11-29%2021-05-01.png

I got error like this Master..

**Comment by aeguy** [comment]
> Hi I have pushed a change that should fix this issue. Can you upgrade your version of `qark` from pypi? The correct version is `qark==2.2.1`.
> 
> `pip install qark --upgrade`

![screenshot from 2018-11-29 21-11-39](https://user-images.githubusercontent.com/36437636/49227342-6e805a80-f41b-11e8-83d0-e5a2099a39b3.png)

i got error like this Master after upgrade
