### ISSUE TITLE
Which all issues covered

### ISSUE THREAD

**Issue by ammyatmail** [linkedin/qark#275]
From QARK wiki its not very clear which all vulnerabilities in android are covered. I have following list, not sure which all are covered, Can you guide me - 

-Does the App deal with any   sensitive data ? How is this data saved ?
-Does the App use any cryptographic   functionality ? Provide source artifacts.
-App   should not log any sensitive data anywhere. Have you verified this ?
-Must   use HTTPS for all network communication, see potential issue here   https://developer.android.com/training/articles/security-ssl
-Use   strong Crypto (Cipher/Digest/MAC/Sig), see   https://developer.android.com/guide/topics/security/cryptography
-Don’t store Credentials in the App
-Use   singleTask/singleInstance/taskAffinity/allowTaskReparenting very carefully;   see potential hijack .   https://www.usenix.org/system/files/conference/usenixsecurity15/sec15-paper-ren-chuangang.pdf
-Use FLAG_SECURE on all sensitive Activities
-Set   android:allowBackup = false.
-Set android:debuggable=false
-For   the exported Content Providers, always verify the URI root when returning fd   associated with this root, see https://support.google.com/faqs/answer/7496913
-Avoid exporting PerferenceActivity. If   required, implement isValidFragment, seec
-Please   check there should not be insecure permission defined in Android Manifest   file

**Comment by nwalsh-lnk** [comment]
Please see here for a list of checks: https://github.com/linkedin/qark#checks
