### ISSUE TITLE
Qark does not include all the issues it found in all plugins

### ISSUE THREAD

**Issue by mrmiywj** [linkedin/qark#279]
We found that, after upgrading to a new version, Qark does not include all the issues it found in the report.
In fact, it only includes the issues found in the manifest scanning.

**Comment by mrmiywj** [comment]
We opened a PR for this issue, #278

**Comment by nwalsh-lnk** [comment]
Thanks for the PR. I noticed similar results and we should be able to fix this quickly. I have commented on the PR
