### ISSUE TITLE
Migrate features in MobSF to Qark

### ISSUE THREAD

**Issue by mrmiywj** [linkedin/qark#282]
Hi Qark team,

We did a comparison of state-of-art mobile security analysis tools in a mobile security course this semester. And we found that there were some vulnerabilities which could be found be by MobSF missing in qark's report. 

Thus we tried to migrate some[ rules in MobSF ](https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/StaticAnalyzer/views/android/android_rules.py)to improve the Qark:

- [x] Detect [more insecure hostname verifiers ](https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/StaticAnalyzer/views/android/android_rules.py#L85)
- [x] Detect [more insecure encryption mode](https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/StaticAnalyzer/views/android/android_rules.py#L74)
- [x] Detect [remote webview debugging](https://github.com/MobSF/Mobile-Security-Framework-MobSF/blob/master/StaticAnalyzer/views/android/android_rules.py#L270)

**Comment by nwalsh-lnk** [comment]
Thanks for the PRs! They are greatly appreciated. Let us know your results when they are ready!
