### ISSUE TITLE
ImportError: No module named apk_builder

### ISSUE THREAD

**Issue by amit343** [linkedin/qark#301]
raceback (most recent call last):
  File "qark.py", line 11, in <module>
    from qark.apk_builder import APKBuilder
  File "/root/Desktop/qark-master/qark/qark.py", line 11, in <module>
    from qark.apk_builder import APKBuilder
ImportError: No module named apk_builder

**Comment by nwalsh1995** [comment]
```
pip install qark
qark --help
```
Do not run using `python qark.py`

**Comment by ZapDos7** [comment]
i got the same problem, and after trying installing it i keep getting segmentation fault.

**Comment by 0rx1** [comment]
If you installed it with sudo, then sudo qark will work just fine

**Comment by joseph-acc** [comment]
If we don't run it using `python qark.py` how do we execute it instead?

**Comment by 0rx1** [comment]
> 
> 
> If we don't run it using `python qark.py` how do we execute it instead?

Simply run `qark `after you `python setup.py install`

**Comment by ajaysingh-qa** [comment]
> > If we don't run it using `python qark.py` how do we execute it instead?
> 
> Simply run `qark `after you `python setup.py install`

By simply running qark.py, it does not work
