### ISSUE TITLE
Installation Fail or Invalid Paths Used

### ISSUE THREAD

**Issue by martialhax** [linkedin/qark#305]
Followed both Installation methods on home page using pip on OSX and then on Kali and "qark" not found when running "qark --help". Followed steps exactly as documented. Even tried on Windows with no errors but something seems to be missing or steps for Installation not correct.
Guidance appreciated.

**Comment by nwalsh-lnk** [comment]
Please post more information including the commands you ran and the output.

**Comment by martialhax** [comment]
So I ran the default install method again... "pip install --user qark" on a new High Sierra build with Python 2.7 Official ( user environment ) and Python 3.5 Official ( user environment ) and Homebrew is installed as well.
It seems to install correctly except I get in the output a message about how "/Users/user/Library/Python/2.7/bin" is not in PATH and should/must be added. Everything seems to be installed in a Python directory. The user I'm testing this under is actually named "user". So running - "/Users/user/Library/Python/2.7/bin/qark --build-path /Users/user/Desktop/" does output the decompiled Java etc. in a build directory on Desktop but report is stuck in -- "/Users/user/Library/Python/2.7/lib/python/site-packages/qark/report/report.html" Through this process I don't see the interface and options I was expecting from write-ups like https://resources.infosecinstitute.com/qark-a-tool-for-automated-android-app-assessments/ (perhaps deprecated). And the report is not using any sort of template or formatting.

Am I missing something?

Thanks for any guidance.

**Comment by nwalsh-lnk** [comment]
@martialhax we have redone the QARK architecture / flow to be more modular and easily accessible. Those guides are out-dated. If you want to download that release you can get it from the Releases tab, but we will not be supporting that code.

We are aware the report does not have any templating currently and that is on our to-do (PRs welcome).
