### ISSUE TITLE
Custom checks

### ISSUE THREAD

**Issue by ammyatmail** [linkedin/qark#314]
Is it possible to add or remove the checks in Qark? As of now only following are supported - https://github.com/linkedin/qark#checks

**Comment by nwalsh-lnk** [comment]
You can add checks by creating your own plugin. Follow any existing plugin code and add your own in `qark/plugins`.

For removing checks, it is being tracked in #149 

If you don't want to wait for that feature to be implemented, you can just remove the python file that contains the check.
