### ISSUE TITLE
No module named 'qark.apk_builder'; 'qark' is not a package (related to issue #288)

### ISSUE THREAD

**Issue by localacct** [linkedin/qark#316]
Hi

I know that a similar issue was filed and closed (#288), but I am also getting the same error and these are what I have tried (on Mac OS)

I followed the steps in the README file
````
  ~ git clone https://github.com/linkedin/qark
  ~ cd qark
  ~ pip install -r requirements.txt
  ~ pip install . --user  # --user is only needed if not using a virtualenv
  ~ qark --help
````

All the installation steps went fine but when I tried ```` qark --help ````, I encountered the ModuleNotFound error. I also tried that command while inside the qark sub folder as well.

After which, I tried ```` python3 qark.py ```` and that's when I encountered the error.

It would seem that I should not be using ```` python ```` to run the file, what steps am I missing?

**Comment by testSatya007** [comment]
I think README is not updated yet.

Please try with following steps.

1. Clone the latest master.
2. Go to qark folder and run the command--pip install qark
3. Check command--qark --help
4. Now try to run --qark --apk /path_apk

Hope this will work.

**Comment by localacct** [comment]
Hi testSatya007

This is what I have tried
````
git clone https://github.com/linkedin/qark.git
cd qark
pip install qark # it says all requirements satisfied
qark --help # command not found
````

Thanks for your help

**Comment by nwalsh-lnk** [comment]
Hi, the application has been installed to where `pip` installs applications on your system. You can find it there. We cannot do anything to fix this issue, its only your system.

**Comment by sathishmepco** [comment]
You need to add "qark" installed location into the System Environment path variable, then only you can able to access the qark from the command line.

In my case it is installed in 
C:\Users\Sathish\appdata\roaming\python\python36\site-packages\qark

Then I have added the below path in the Environment path to access qark C:\Users\Sathish\appdata\roaming\python\python36\Scripts

To get the installed location of QARK, use the below command
$ pip show qark
