### ISSUE TITLE
Is readme outdated or what??

### ISSUE THREAD

**Issue by arthurmazer** [linkedin/qark#332]
I followed the instructions a thousand times and and all that i got is: Command 'qark' not found, fml, can we have an actual guide on how to properly install this ?

**Comment by squeeish** [comment]
`pip show qark`

Under Location, you should see something like `/Users/squeeish/Library/Python/2.7/lib/python/site-packages`

Add `/Users/squeeish/Library/Python/2.7/bin` to your $PATH

**Comment by arthurmazer** [comment]
thank you so much!
