### ISSUE TITLE
I'd like to have a simple report

### ISSUE THREAD

**Issue by komatatsu** [linkedin/qark#35]
Hi
I tried Qark and its result was good for me.

But then, I have one question for it.
Does qurk have any simple report features to integrate with CI such as Jenkins ?
If it doesn't have, do you have alternative to integrate with CI ? 
For example, exporting the result as xml.

I'd like to see the result via Dashboard provided by CI.

Thanks

**Comment by nwalsh1995** [comment]
This has been finished with PR #120
