### ISSUE TITLE
RecursionError: maximum recursion depth exceeded

### ISSUE THREAD

**Issue by MRazian** [linkedin/qark#353]
`Python 3.7`

After De-compiling, it starts 

> Running scans

 (the following log)
Decompiling com/google/protobuf/GeneratedMessage...
Running scans...

But it took a lot of time and printed 
`RecursionError: maximum recursion depth exceeded`

I tested with different applications but the results are same.

**Comment by MRazian** [comment]
I found out that in Python 3.6 it works properly.

**Comment by nocomp** [comment]
hi @MRazian i have tje same issue, how do you force python3.6 to be used ?
thxx for helping

**Comment by MRazian** [comment]
You can use virtualenv and create a virtual environment for Python3.6 like
following command:

virtualenv -p Python3.6 venv
source venv/bin/activate

Thanks

**Comment by nocomp** [comment]
Thxx a lot i ll try
Do you get successul apk generated? Mine always force close
Thxx for your time

**Comment by MRazian** [comment]
Sorry for late response. I haven't tried this feature yet. Please let me know if you could generate apk.
Tnx

**Comment by nocomp** [comment]
Hi @MRazian 
Yes i am able to generae an apk but it doesnt wok.
Force close every time you run it :/
Gettin despaired to get this tool working propelly one day...  It seems that all the ppl supporting it left the boat :(
Thx for your assistance, truelly appreciate

**Comment by joseph-acc** [comment]
I was unable to get a scan with Python 3.6

**Comment by AhmadQ1992** [comment]
I have the same problem
