### ISSUE TITLE
Debuglevel argument ignored

### ISSUE THREAD

**Issue by fmussio** [linkedin/qark#40]
The debuglevel argument (-d or --debug) seems to be always ignored. I tried "-debug 10", as i wanted to see details of execution, but nothing changed... both log handlers (console and file) kept their default log level (INFO). Another problem is that the file created inside "logs" folder is always named "info.log", despite the log level.

In addition, as long as the debuglevel argument refers to the log level, i think it should be named "-l" or "--loglevel" instead.

best regards,

**Comment by SecBro1** [comment]
The valid values are : 10,20,30,40,50,60.

Try increasing values and see if you get any different output
