### ISSUE TITLE
Main Activity export Warning 

### ISSUE THREAD

**Issue by mabdi** [linkedin/qark#47]
Main (launcher) activity is a special activity; it needs true export and no permission restriction.
It's better to warn differently for launcher activities.

qark output:

> INFO - Checking activity
> WARNING - The following activity are exported, but not protected by any permissions. Failing to protect activity could leave them vulnerable to attack by malicious apps. The activity should be reviewed for vulnerabilities, such as injection and information leakage.
>           com.foo.bar.Main

Sample Android Manifest for a launcher:

```
        <activity android:label="@string/app_caption" android:name="com.foo.bar.Main" android:theme="@android:style/Theme.NoTitleBar.Fullscreen">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
```

**Comment by SecBro1** [comment]
True, will fix

**Comment by nwalsh-lnk** [comment]
We have just pushed a new version of QARK that solves a lot of problems and enhances the code.

As a result we will be closing out all tickets for the older version since we no longer support it. If this issue persists in the new version please create a new ticket.
