### ISSUE TITLE
False alarm for The Custom Permission Problem

### ISSUE THREAD

**Issue by mabdi** [linkedin/qark#48]
According to [https://github.com/commonsguy/cwac-security/blob/master/PERMS.md](https://github.com/commonsguy/cwac-security/blob/master/PERMS.md) a custom permission problem requires a custom permission define. If no new permission is defined or the used permission for a module is a known permission a custom permission vulnerability cannot happen. 

qark output:

> POTENTIAL VULNERABILITY - The following receiver are exported and protected by a permission, but the permission can be obtained by malicious apps installed prior to this one. More info: https://github.com/commonsguy/cwac-security/blob/master/PERMS.md. Failing to protect receiver could leave them vulnerable to attack by malicious apps. The receiver should be reviewed for vulnerabilities, such as injection and information leakage.
>           com.google.android.gcm.GCMBroadcastReceiver
>                     com.google.android.c2dm.permission.SEND

Manifest:

```
       <receiver android:name="com.google.android.gcm.GCMBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
                <action android:name="com.google.android.c2dm.intent.REGISTRATION"/>
                <category android:name="com.androidexample.gcm"/>
            </intent-filter>
        </receiver>
```

**Comment by SecBro1** [comment]
This check should only alert when there is a custom permission defined. If you are seeing something else, please indicate which app you are scanning that provides a false positive.

**Comment by mabdi** [comment]
my app's manifest is sth like this:

```
<?xml version="1.0" encoding="utf-8" standalone="no"?>
<manifest xmlns:android="http://schemas.android.com/apk/res/android" package="com.foobar.PushNotify">
    <application android:debuggable="true" android:icon="@drawable/_app_icon" android:label="@string/app_name" android:name="com.foobar.PushNotify.Controller" android:theme="@style/AppTheme">
        <activity android:label="@string/app_caption" android:name="com.foobar.PushNotify.Registration" android:theme="@android:style/Theme.NoTitleBar.Fullscreen">
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
            <intent-filter>
                <action android:name="android.intent.action.VIEW"/>
                <action android:name="android.intent.action.DELETE"/>
                <category android:name="android.intent.category.DEFAULT"/>
                <data android:scheme="com.idrivecare.familypro"/>
            </intent-filter>
        </activity>
        <activity android:configChanges="keyboardHidden|orientation" android:label="@string/app_caption" android:name="com.foobar.PushNotify.MyActivity" android:theme="@android:style/Theme.NoTitleBar.Fullscreen"/>
        <activity android:configChanges="keyboardHidden|orientation" android:label="@string/app_caption" android:name="com.foobar.PushNotify.OtpVerify" android:theme="@android:style/Theme.NoTitleBar.Fullscreen"/>
        <receiver android:name="com.google.android.gcm.GCMBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND">
            <intent-filter>
                <action android:name="com.google.android.c2dm.intent.RECEIVE"/>
                <action android:name="com.google.android.c2dm.intent.REGISTRATION"/>
                <category android:name="com.androidexample.gcm"/>
            </intent-filter>
        </receiver>
        <service android:name="com.foobar.PushNotify.GCMIntentService"/>
    </application>
    <uses-permission android:name="android.permission.INTERNET"/>
    <uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE"/>
    <uses-permission android:name="android.permission.WAKE_LOCK"/>
    <permission android:name="com.foobar.PushNotify.permission.C2D_MESSAGE" android:protectionLevel="signature"/>
    <uses-permission android:name="com.foobar.PushNotify.permission.C2D_MESSAGE"/>
    <uses-permission android:name="com.google.android.c2dm.permission.RECEIVE"/>
    <uses-permission android:name="android.permission.ACCESS_NETWORK_STATE"/>
    <uses-permission android:name="android.permission.VIBRATE"/>
</manifest>
```
and qark result:

> INFO - Determined minimum SDK version to be:8
> WARNING - Logs are world readable on pre-4.1 devices. A malicious app could potentially retrieve sensitive data from the logs.
> INFO - Setting maxSdkVersion not recommended, unless you explicitly want to prevent use on newer versions.
> ISSUES - APP COMPONENT ATTACK SURFACE
> WARNING - The backup element is not specified in the manifest, which therefore defaults to true. Potential for data theft via local attacks via adb backup, if the device has USB debugging enabled (not common). More info: http://developer.android.com/reference/android/R.attr.html#allowBackup
> POTENTIAL VULNERABILITY - The android:debuggable flag is manually set to true in the AndroidManifest.xml. This will cause your application to be debuggable in production builds and can result in data leakage and other security issues. It is not necessary to set the android:debuggable flag in the manifest, it will be set appropriately automatically by the tools. More info: http://developer.android.com/guide/topics/manifest/application-element.html#debug
> INFO - Checking provider
> INFO - Checking activity
> WARNING - The following activity are exported, but not protected by any permissions. Failing to protect activity could leave them vulnerable to attack by malicious apps. The activity should be reviewed for vulnerabilities, such as injection and information leakage.
>           com.foobar.PayamResan.Registration
> INFO - Checking activity-alias
> INFO - Checking services
> INFO - Checking receivers
> POTENTIAL VULNERABILITY - The following receiver are exported and protected by a permission, but the permission can be obtained by malicious apps installed prior to this one. More info: https://github.com/commonsguy/cwac-security/blob/master/PERMS.md. Failing to protect receiver could leave them vulnerable to attack by malicious apps. The receiver should be reviewed for vulnerabilities, such as injection and information leakage.
>           com.google.android.gcm.GCMBroadcastReceiver
>                     com.google.android.c2dm.permission.SEND

**Comment by mabdi** [comment]
We have a permission define, but defined permission is not used for this receiver.

`    <permission android:name="com.foobar.PushNotify.permission.C2D_MESSAGE" android:protectionLevel="signature"/>
`
`        <receiver android:name="com.google.android.gcm.GCMBroadcastReceiver" android:permission="com.google.android.c2dm.permission.SEND">
`

**Comment by nwalsh-lnk** [comment]
We have just pushed a new version of QARK that solves a lot of problems and enhances the code.

As a result we will be closing out all tickets for the older version since we no longer support it. If this issue persists in the new version please create a new ticket.
