### ISSUE TITLE
Detect when build of attack APK fails

### ISSUE THREAD

**Issue by SecBro1** [linkedin/qark#56]
From https://github.com/linkedin/qark/issues/12, someone reported that they are still prompted to install the attack APK, even after the build failed.

We should detect the build failure and respond differently.

**Comment by maheshtata2020** [comment]
`Error: org.gradle.process.internal.ExecException: A problem occurred starting process 'command '/root/Desktop/qark/qark/android-sdk_r24.3.4-linux/android-sdk-linux/build-tools/21.1.2/aapt''
:app:mergeDebugResources FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:mergeDebugResources'.
> Error: org.gradle.process.internal.ExecException: A problem occurred starting process 'command '/root/Desktop/qark/qark/android-sdk_r24.3.4-linux/android-sdk-linux/build-tools/21.1.2/aapt''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED`

**Comment by subrosaassociates** [comment]
I'd love to see some documentation around ensuring all checks are met to get the most out of qark, I asked my infosec friends on the tweets if they'd successfully used qark and the general feedback was 'it doesn't work properly' 

... but i'm hoping it's more about documentation and dependency expectations 

 I have the build failed too

**Comment by nwalsh1995** [comment]
@maheshtata2020 can you make this a separate issue and we can work to fix it?

@subrosaassociates we are aware of some problems and are working on fixing them. The codebase is old and has some growing pains. If you can create issues on what you are having problems with we can try to get it fixed.

**Comment by nwalsh-lnk** [comment]
We have just pushed a new version of QARK that solves a lot of problems and enhances the code.

As a result we will be closing out all tickets for the older version since we no longer support it. If this issue persists in the new version please create a new ticket.
