### ISSUE TITLE
No module named qark.modules.IssueType

### ISSUE THREAD

**Issue by k7jto** [linkedin/qark#62]
Just cloned the latest version of qark into ~/Tools/qark. Running "python qarkMain.py" I get an ImportError: No module named qark.modules.IssueType.

- Running Ubuntu 16
- Python 2.7.12 /usr/bin/python
- PYTHONPATH: /Tools/qark/qark/modules:/Tools/qark/qark:
- Command:
```
jim@jimPC:~/Tools/qark/qark$ python qarkMain.py
Traceback (most recent call last):
  File "qarkMain.py", line 30, in <module>
    from qark.modules.IssueType import IssueSeverity
ImportError: No module named qark.modules.IssueType
```

It's gotta be something simple. I've tried quite a few things (including adding the /modules dir to my PYTHONPATH, obviously) to no avail. The tests, of course, fail with the same error and haven't provided additional insight.

**Comment by k7jto** [comment]
Two updates: 
1) runs great on my Mac (OSX)
2) I noticed I'm running Java 1.8. Perhaps that's the issue?

**Comment by tushardalvi** [comment]
Thanks for the feedback. We will investigate the issue.
CC @dhaugh

**Comment by dhaugh** [comment]
Did they add the root directory to the PYTHONPATH like in the Readme, or
pip install?

On Nov 15, 2016 10:16 AM, "Tushar Dalvi" <notifications@github.com> wrote:

Thanks for the feedback. We will investigate the issue.
CC @dhaugh <https://github.com/dhaugh>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/linkedin/qark/issues/62#issuecomment-260718492>, or mute
the thread

**Comment by nick3085** [comment]
Got the same issue, any luck investigating this?

**Comment by elliott-accolade** [comment]
I'm also facing this issue. 

MacOSX
Java 1.8
Python 2.7.12

**Comment by neilatli** [comment]
I reproduced the issue on Ubuntu. Working on a fix.

**Comment by testSatya007** [comment]
In latest cloned code. qarkMain.py is missing. What is the reason. I am using windows and when running the "python qark.py" command, I am getting error like 

Traceback (most recent call last):
  File "qark.py", line 11, in <module>
    from qark.apk_builder import APKBuilder
  File "F:\PenTesting Tools\QARK\qark\qark\qark.py", line 11, in <module>
    from qark.apk_builder import APKBuilder
ModuleNotFoundError: No module named 'qark.apk_builder'; 'qark' is not a package
