### ISSUE TITLE
Need a more accommodating method of finding the compileSdkVersion (have solution!)

### ISSUE THREAD

**Issue by elliott-accolade** [linkedin/qark#64]
We're not specifying our compileSdkVersion in the AndroidManifest, so we're relying on the find_gradle() function to determine our compileSdkVersion (which I think you're referring to as the MIN SdkVersion elsewhere in the script).

I noticed that your regex is searching for the string 'def _compileSdkVersion = XX', which wasn't finding our compileSdkVersion (which we've defined as 'compileSdkVersion 24'). 

I edited the regex from yours:
		`matches=common.text_scan(files,r'def\s_compileSdkVersion\s*=\s*[0-9]+')`

to this one:
		`matches=common.text_scan(files,r'.*(compileSdkVersion)(\s*|\s*=\s*)([0-9]+)')`

The second one finds both yours and mine. I'd be happy to do a pull request if you'd permit it.

I have another question, if you don't mind answering here:
In that same method (find_gradle()), you're looking to make sure that matches == 2, but I only ever have one match, so the script does not find my sdk version, even though it's valid. I saw your developer's note referring to an 'empty first element' - what element are you referring to?

Thank you very much in advance for addressing these issues! Fantastic work.

**Comment by nwalsh-lnk** [comment]
We have just pushed a new version of QARK that solves a lot of problems and enhances the code.

As a result we will be closing out all tickets for the older version since we no longer support it. If this issue persists in the new version please create a new ticket.
