### ISSUE TITLE
Disable LALR regeneration

### ISSUE THREAD

**Issue by rip32700** [linkedin/qark#68]
Hi,

I am trying to include qark in my web app. After each save I get "Generating LALR tables" several times. I tried to set all the write_table flags in lib/ply/yacc.py to False/0, but it still generates the tables every time.

Can anybody help me what I am supposed to do to disable the regeneration of the LALR tables?

Thanks in advance

**Comment by tushardalvi** [comment]
The LALR tables are generated only on a fresh install and not on subsequent runs. If you are still having issues, you could try one of the solutions listed here: https://stackoverflow.com/questions/12644902/how-to-prevent-table-regeneration-in-ply

Cheers
