### ISSUE TITLE
Unable to build apk in seamless mode

### ISSUE THREAD

**Issue by pogodpi** [linkedin/qark#72]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find com.android.support:appcompat-v7:22.2.1.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/appcompat-v7/22.2.1/appcompat-v7-22.2.1.pom
         https://jcenter.bintray.com/com/android/support/appcompat-v7/22.2.1/appcompat-v7-22.2.1.jar
     Required by:
         qark:app:unspecified
   > Could not find com.android.support:design:22.2.1.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/design/22.2.1/design-22.2.1.pom
         https://jcenter.bintray.com/com/android/support/design/22.2.1/design-22.2.1.jar
     Required by:
         qark:app:unspecified
   > Could not find com.android.support:recyclerview-v7:22.2.1.
     Searched in the following locations:
         https://jcenter.bintray.com/com/android/support/recyclerview-v7/22.2.1/recyclerview-v7-22.2.1.pom
         https://jcenter.bintray.com/com/android/support/recyclerview-v7/22.2.1/recyclerview-v7-22.2.1.jar
     Required by:
         qark:app:unspecified

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 44.787 secs

**Comment by nwalsh1995** [comment]
Hi @pogodpi  sorry for the late response but this gained traction. This issue is because the following dependencies are declared in our `build.gradle` file but your build didn't manage to find them online to download.

```
com.android.support:appcompat-v7:22.2.1
com.android.support:design:22.2.1
com.android.support:recyclerview-v7:22.2.1
```

I would suggest to try to install these dependencies manually and determine what is going wrong from there.

**Comment by nwalsh-lnk** [comment]
We have just pushed a new version of QARK that solves a lot of problems and enhances the code.

As a result we will be closing out all tickets for the older version since we no longer support it. If this issue persists in the new version please create a new ticket.
