### ISSUE TITLE
Not able to run qark

### ISSUE THREAD

**Issue by pentagramz** [linkedin/qark#75]
Please help
![qark](https://cloud.githubusercontent.com/assets/7072014/22685741/82ff1d98-ed47-11e6-99e6-eca251dc1b1a.PNG)

**Comment by dhaugh** [comment]
Hi @pentagramz 
It looks like you're running an old version of qark. Please try again with the latest version.

**Comment by pentagramz** [comment]
i downloaded latest version same problem

**Comment by aarvee11** [comment]
@pentagramz check the permissions of the apk file. Seems to be a typical permissions issue
