### ISSUE TITLE
Not a valid APK if the filename contains special characters. Rename it, issue is fixed 

### ISSUE THREAD

**Issue by aarvee11** [linkedin/qark#76]
Small bug, can be ignored too. Submitting the issue just for user convenience!
=================================================
AppName: example-1.7\(106\)-27-08-2016-playStore-release.apk
=================================================
Please enter the full path to your APK (ex. /foo/bar/pineapple.apk):
Path:/Users/venkatashivakumar/Desktop/example-1.7\(106\)-27-08-2016-playStore-release.apk                                                                                                     
INFO - Unpacking /Users/venkatashivakumar/Desktop/example-1.7\(106\)-27-08-2016-playStore-release.apk
ERROR - Not a valid APK. Please try again

=====================================
Renamed the appname to example.apk - Works !
=====================================
Do you want to:
[1] Provide a path to an APK
[2] Pull an existing APK from the device?

Enter your choice:1

Please enter the full path to your APK (ex. /foo/bar/pineapple.apk):
Path:/Users/venkatashivakumar/Desktop/example.apk
INFO - Unpacking /Users/venkatashivakumar/Desktop/example.apk
INFO - Zipfile: <zipfile.ZipFile object at 0x10a559450>
INFO - Extracted APK to /Users/venkatashivakumar/Desktop/example/
/Users/venkatashivakumar/Desktop/apktool/AndroidManifest.xml
Inspect Manifest?[y/n]y

**Comment by aniruddha-stqc** [comment]
Alternate approach:

I was working with an APK created using PhoneGap (Apache Cordova). Mere changing the name did not resolve my issue. So, I installed the APK on my mobile device. Connected to PC. Turned USB debug on. Chose "[2] Pull an existing APK from the device?"  Then the took presented me all the apps installed in my device, from where I chose my required APK.

**Comment by nwalsh-lnk** [comment]
We have just pushed a new version of QARK that solves a lot of problems and enhances the code.

As a result we will be closing out all tickets for the older version since we no longer support it. If this issue persists in the new version please create a new ticket.
