### ISSUE TITLE
Plugin to detect insecure use of onReceivedSslError

### ISSUE THREAD

**Issue by ikkisoft** [linkedin/qark#80]
When loading WebViews, it is possible to handle TLS errors using the method _onReceivedSslError(WebView view, SslErrorHandler handler, SslError error)_

https://developer.android.com/reference/android/webkit/WebViewClient.html#onReceivedSslError

Unfortunately, it is also common practice to skip the error:

```
 @Override
        public void onReceivedSslError(WebView view, SslErrorHandler handler, SslError error) {
            handler.proceed();
        }
```

We could make a plugin to detect this use, since it bypasses cert pinning and other protections.

**Comment by tushardalvi** [comment]
Thanks for the input Luca. The latest update can detect this condition.

Cheers!
