### ISSUE TITLE
supporting Build Tools 25

### ISSUE THREAD

**Issue by ChenSiLiang** [linkedin/qark#83]
I use build tools 25.0.2 in my project.
error occurs when checking my apk with qark.
```
* What went wrong:
A problem occurred configuring project ':app'.
> failed to find Build Tools revision 25.0.2
```

**Comment by nwalsh-lnk** [comment]
We have just pushed a new version of QARK that solves a lot of problems and enhances the code.

As a result we will be closing out all tickets for the older version since we no longer support it. If this issue persists in the new version please create a new ticket.
