### ISSUE TITLE
[GRADLE PROBLEM] I need to download through proxy

### ISSUE THREAD

**Issue by wigrus** [linkedin/qark#84]
Hello,
I have a problem with downloading and installing gradle. I need to download things through proxy. Proxcychains won't do the job, because its WDAP. Which directory could contain downloaded gradle, or which script shouId I edit to be able to download through proxy?

![qark gradle problem](https://cloud.githubusercontent.com/assets/17358005/25270175/f44e31f2-267f-11e7-84b0-c67366401305.png)

**Comment by nwalsh-lnk** [comment]
Hi @wigrus, we subprocess the `gradlew` command in the [sdkManager](https://github.com/linkedin/qark/blob/73fd73448ad2085110bb1e1f4b9096321de6c979/qark/modules/sdkManager.py)
