### ISSUE TITLE
Feature Enhancement Request: Potential vulnerability - severity rating

### ISSUE THREAD

**Issue by rajkiran4work** [linkedin/qark#85]
I think it would be a helpful if there is severity rating like High/Medium/Low(or score) to the potential vulnerability issues.
Any chance if we can get it ?

**Comment by sarveshkapre** [comment]
Hi,
That's a good suggestion but we have intentionally decided not to add severity rating as we want users to take educated decision on the findings.
Thank you for sharing your idea. 

Cheers!
