### ISSUE TITLE
Issues visible on the shall are not reported in the HTML report

### ISSUE THREAD

**Issue by mbaluda** [linkedin/qark#87]
I'm seeing a misalignment between the report and the console logs.
for example, the following appears on the console but not in the HTML report
POTENTIAL VULNERABILITY - Call to addJavascriptInterface() is detected on instance of WebView in file: ...

Can anyone explain this inconsistency?

**Comment by nwalsh1995** [comment]
Hi @mbaluda, this should be fixed with PR #133. Please update and see if the issues are being correctly added now.
