### ISSUE TITLE
Qark does not detect a number of vulnerabilities

### ISSUE THREAD

**Issue by JoyMitra** [linkedin/qark#90]
Hi,

I am evaluating android security tools as part of my research. I am measuring each tools effectiveness against a benchmark (https://bitbucket.org/secure-it-i/android-app-vulnerability-benchmarks). My experiments suggest that Qark detected only 2 out of the 25 vulnerabilities in that benchmark. The benchmarks detected successfully by Qark were :

- StickyBroadcast
- InvalidCertificateAuthority

All other benchmarks were not detected. Please visit the benchmark URL mentioned above to get a complete list of the vulnerability benchmarks.

Please let me know if you want to more details about my experiment and how it was conducted.

**Comment by sarveshkapre** [comment]
Hey,

Thank you for sharing your valuable feedback. We have reviewed all the benchmarks from the Ghera repo and updated Qark to detect all the high impact issues.

Cheers 👍

**Comment by JoyMitra** [comment]
Hey,

Thanks for getting back. Where can I find the updated version? In releases?

**Comment by sarveshkapre** [comment]
Yes. All the changes are merged in the master branch.
We will also be updating more checks in next few days.

**Comment by neilatli** [comment]
Hi @JoyMitra, thanks for your valuable contribution to this area of research!

We have merged all of the new checks into the master branch and as @sarveshkapre mentioned, Qark is now detecting all of the high impact issues in Ghera.

Please feel free to retest Qark and let us know if your results vary.

**Comment by JoyMitra** [comment]
@neilatli, Thanks for getting back. Can you please let me know the *commit id* I need to check out?

**Comment by nwalsh-lnk** [comment]
These checks were added under the [plugins](https://github.com/linkedin/qark/tree/master/qark/plugins) folder. Please check there to see the added checks. Closing.
